### ISSUE TITLE
sstabledump failed because AzureSnitch ClassNotFoundException

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla-tools-java#338]
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

since 5.2 we officially support Azure, and in this job, we are upgrading from 5.2.6 to 2023.1.0-rc8
in this test, we run the following command, to ensure it works:
```
for i in `sudo find /var/lib/scylla/data/keyspace_complex/ -type f |grep -v manifest.json |grep -v snapshots |head -n 1`; do echo $i; sudo sstabledump $i 1>/tmp/sstabledump.output || exit 1; done
```

but it failed:
```
Exit code: 1
Stdout:
/var/lib/scylla/data/keyspace_complex/user_with_ck-93a3e700360611eebccc2e7155ec929d/me-57-big-Index.db
Stderr:
at org.apache.cassandra.tools.SSTableExport.<clinit>(SSTableExport.java:69)
Caused by: java.lang.ClassNotFoundException: org.apache.cassandra.locator.AzureSnitch
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at org.apache.cassandra.utils.FBUtilities.classForName(FBUtilities.java:556)
... 6 more
```

it happened once we upgraded all the nodes

## How frequently does it reproduce?

did run it once, but it is clear that it will fail on every run

## Installation details

Kernel Version: 5.15.0-1042-azure
Scylla version (or git commit hash): `5.2.6-20230730.58acf071bf28` with build-id `17961be569f8503b27ff284a8de1e00a9d83811e`
Target Scylla version (or git commit hash): `2023.1.0~rc8-20230731.b6f7c5a6910c` with build-id `f6e718548e76ccf3564ed2387b6582ba8d37793c`

Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-a0dba1a8-eastus-4 (172.190.112.196 | 10.0.0.8) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a0dba1a8-eastus-3 (172.190.117.226 | 10.0.0.7) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a0dba1a8-eastus-2 (172.190.117.166 | 10.0.0.6) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a0dba1a8-eastus-1 (172.190.117.164 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.2.6-x86_64-2023-08-01T05-27-35` (azure: eastus)

Test: `rolling-upgrade-azure-image-test`
Test id: `a0dba1a8-303f-46d7-8aba-0986c71db060`
Test name: `enterprise-2023.1/rolling-upgrade/rolling-upgrade-azure-image-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d673e429b75e4d7643c4f0dc85e3933d5425e886/test-cases/upgrades/rolling-upgrade.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a0dba1a8-303f-46d7-8aba-0986c71db060`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a0dba1a8-303f-46d7-8aba-0986c71db060)
- Show all stored logs command: `$ hydra investigate show-logs a0dba1a8-303f-46d7-8aba-0986c71db060`

## Logs:
- **db-cluster-a0dba1a8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/db-cluster-a0dba1a8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/db-cluster-a0dba1a8.tar.gz)
- **sct-runner-events-a0dba1a8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/sct-runner-events-a0dba1a8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/sct-runner-events-a0dba1a8.tar.gz)
- **sct-a0dba1a8.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/sct-a0dba1a8.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/sct-a0dba1a8.log.tar.gz)
- **monitor-set-a0dba1a8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/monitor-set-a0dba1a8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/monitor-set-a0dba1a8.tar.gz)
- **loader-set-a0dba1a8.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/loader-set-a0dba1a8.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a0dba1a8-303f-46d7-8aba-0986c71db060/20230808_192101/loader-set-a0dba1a8.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/10/)
[Argus](https://argus.scylladb.com/test/fc869933-dcdf-4130-9dd4-b9c0c4c10b53/runs?additionalRuns[]=a0dba1a8-303f-46d7-8aba-0986c71db060)
</details>

**Comment by fgelcer** [comment]
@DoronArazii FYI

**Comment by soyacz** [comment]
Issue reproduced but it's not reproducing in all the runs.
## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.


## Installation details

Kernel Version: 5.15.0-1042-azure
Scylla version (or git commit hash): `5.2.6-20230730.58acf071bf28` with build-id `17961be569f8503b27ff284a8de1e00a9d83811e`
Target Scylla version (or git commit hash): `2023.1.0-20230813.68e9cef1baf7` with build-id `c7f9855620b984af24957d7ab0bd8054306d182e`




Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-a838df17-eastus-4 (4.236.182.172 | 10.0.0.8) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a838df17-eastus-3 (4.236.182.155 | 10.0.0.7) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a838df17-eastus-2 (4.236.182.150 | 10.0.0.6) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-a838df17-eastus-1 (4.236.182.96 | 10.0.0.5) (shards: 7)


OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-5.2.6-x86_64-2023-08-01T05-27-35` (azure: eastus)

Test: `rolling-upgrade-azure-image-test`
Test id: `a838df17-0472-45e1-90ce-0bf4422a23e3`
Test name: `enterprise-2023.1/rolling-upgrade/rolling-upgrade-azure-image-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3169a443f7de5763aa2f22d44d1d6b950dd47f06/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor a838df17-0472-45e1-90ce-0bf4422a23e3`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a838df17-0472-45e1-90ce-0bf4422a23e3)
- Show all stored logs command: `$ hydra investigate show-logs a838df17-0472-45e1-90ce-0bf4422a23e3`


## Logs:
- **db-cluster-a838df17.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/db-cluster-a838df17.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/db-cluster-a838df17.tar.gz)
- **sct-runner-events-a838df17.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/sct-runner-events-a838df17.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/sct-runner-events-a838df17.tar.gz)
- **sct-a838df17.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/sct-a838df17.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/sct-a838df17.log.tar.gz)
- **monitor-set-a838df17.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/monitor-set-a838df17.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/monitor-set-a838df17.tar.gz)
- **loader-set-a838df17.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/loader-set-a838df17.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a838df17-0472-45e1-90ce-0bf4422a23e3/20230815_103803/loader-set-a838df17.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/13/)
[Argus](https://argus.scylladb.com/test/fc869933-dcdf-4130-9dd4-b9c0c4c10b53/runs?additionalRuns[]=a838df17-0472-45e1-90ce-0bf4422a23e3)
</details>

**Comment by juliayakovlev** [comment]
The issue reproduced with `2023.1.1-20230903`
Does this issue should be opened in `scylla-enterprise-tools-java` as well?


## Issue description

- [ ] This issue is a regression.
- [ ] It is unknown if this issue is a regression.

*Describe your issue in detail and steps it took to produce it.*

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Kernel Version: 5.15.0-1045-azure
Scylla version (or git commit hash): `2023.1.1-20230903.68fa1ae4eb94` with build-id `15dd29a34d99a3c9b2196c362264a50c1579085a`
Target Scylla version (or git commit hash): `2023.1.1-20230906.f4633ec973b0` with build-id `b454e7a22f80cf71a33b2f39e47127225e8fbc13`




Cluster size: 4 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- rolling-upgrade--ubuntu-focal-db-node-7ef06c73-eastus-4 (172.178.109.57 | 10.0.0.8) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-7ef06c73-eastus-3 (172.178.109.45 | 10.0.0.7) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-7ef06c73-eastus-2 (172.178.109.38 | 10.0.0.6) (shards: 7)
- rolling-upgrade--ubuntu-focal-db-node-7ef06c73-eastus-1 (172.178.109.34 | 10.0.0.5) (shards: 7)


OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/SCYLLA-IMAGES/providers/Microsoft.Compute/images/scylla-2023.1.1-x86_64-2023-09-03T19-09-47` (azure: eastus)

Test: `rolling-upgrade-azure-image-test`
Test id: `7ef06c73-07f3-466f-9836-e2e5e64e54dd`
Test name: `enterprise-2023.1/rolling-upgrade/rolling-upgrade-azure-image-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/7c9830422ce7f997f031e89ba1567f8115df9764/test-cases/upgrades/rolling-upgrade.yaml)


<details>
<summary>
Logs and commands
</summary>


- Restore Monitor Stack command: `$ hydra investigate show-monitor 7ef06c73-07f3-466f-9836-e2e5e64e54dd`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7ef06c73-07f3-466f-9836-e2e5e64e54dd)
- Show all stored logs command: `$ hydra investigate show-logs 7ef06c73-07f3-466f-9836-e2e5e64e54dd`


## Logs:
- **db-cluster-7ef06c73.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/db-cluster-7ef06c73.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/db-cluster-7ef06c73.tar.gz)
- **sct-runner-events-7ef06c73.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/sct-runner-events-7ef06c73.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/sct-runner-events-7ef06c73.tar.gz)
- **sct-7ef06c73.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/sct-7ef06c73.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/sct-7ef06c73.log.tar.gz)
- **monitor-set-7ef06c73.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/monitor-set-7ef06c73.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/monitor-set-7ef06c73.tar.gz)
- **loader-set-7ef06c73.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/loader-set-7ef06c73.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7ef06c73-07f3-466f-9836-e2e5e64e54dd/20230906_152409/loader-set-7ef06c73.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2023.1/job/rolling-upgrade/job/rolling-upgrade-azure-image-test/16/)
[Argus](https://argus.scylladb.com/test/fc869933-dcdf-4130-9dd4-b9c0c4c10b53/runs?additionalRuns[]=7ef06c73-07f3-466f-9836-e2e5e64e54dd)
</details>

**Comment by mykaul** [comment]
It will take less time for @denesb to replace sstabledump with a native tool than fix this, I reckon.

**Comment by denesb** [comment]
`scylla sstable` is ready to use for some time now. It is also included in 5.2. There is one inconvenience though, the 5.2. version of scylla-sstable does not yet know to read the schema from system tables, so it has to be provided in a separate `schema.cql` file.

**Comment by fruch** [comment]
> `scylla sstable` is ready to use for some time now. It is also included in 5.2. There is one inconvenience though, the 5.2. version of scylla-sstable does not yet know to read the schema from system tables, so it has to be provided in a separate `schema.cql` file.

so a snapshot is needed  first ? to generate the `schema.cql`?

can you backport the code that read the system tables ? into 5.2/2023.1 ?

**Comment by denesb** [comment]
> > `scylla sstable` is ready to use for some time now. It is also included in 5.2. There is one inconvenience though, the 5.2. version of scylla-sstable does not yet know to read the schema from system tables, so it has to be provided in a separate `schema.cql` file.
> 
> so a snapshot is needed first ? to generate the `schema.cql`?

Either that or produce it manually.
 
> can you backport the code that read the system tables ? into 5.2/2023.1 ?

I will look into backporting it. It is a well delimited change, not affecting other parts of the system, so it is not a risk to scylla itself.

**Comment by denesb** [comment]
Backport PR: https://github.com/scylladb/scylladb/pull/15386

**Comment by yaronkaikov** [comment]
@denesb I guess this can be closed , right ?

**Comment by denesb** [comment]
> @denesb I guess this can be closed , right ?

The backport PR was not merged yet.

**Comment by mykaul** [comment]
This is unlikely to get fixed, as newer (native scylla sstable ... tool) is working well and we have no plans to fix it for the Java based tool.

**Comment by denesb** [comment]
It seems like @yaronkaikov considered this good to close, as soon as https://github.com/scylladb/scylladb/pull/15386 lands in 5.2, and it already did.

**Comment by mykaul** [comment]
> It seems like @yaronkaikov considered this good to close, as soon as [scylladb/scylladb#15386](https://github.com/scylladb/scylladb/pull/15386) lands in 5.2, and it already did.

@denesb - I'm not sure I understand - was this fixed? If it was, then it wasn't fixed properly (see https://github.com/scylladb/scylladb/issues/17659 )

**Comment by denesb** [comment]
> > It seems like @yaronkaikov considered this good to close, as soon as [scylladb/scylladb#15386](https://github.com/scylladb/scylladb/pull/15386) lands in 5.2, and it already did.
> 
> @denesb - I'm not sure I understand - was this fixed? If it was, then it wasn't fixed properly (see [scylladb/scylladb#17659](https://github.com/scylladb/scylladb/issues/17659) )

No, we didn't do anything with `sstabledump`. Instead, the "fix" was backporting enough of the `scylla-sstable` improvements that went in after 5.2, to make it usable enough to replace `sstabledump` in daily usage.

**Comment by fruch** [comment]
> > > It seems like @yaronkaikov considered this good to close, as soon as [scylladb/scylladb#15386](https://github.com/scylladb/scylladb/pull/15386) lands in 5.2, and it already did.
> > 
> > 
> > @denesb - I'm not sure I understand - was this fixed? If it was, then it wasn't fixed properly (see [scylladb/scylladb#17659](https://github.com/scylladb/scylladb/issues/17659) )
> 
> No, we didn't do anything with `sstabledump`. Instead, the "fix" was backporting enough of the `scylla-sstable` improvements that went in after 5.2, to make it usable enough to replace `sstabledump` in daily usage.

so it's there in 5.2, and we can backport the usage of the new tool into SCT branch-5.2 ?

**Comment by fruch** [comment]
@vponomaryov 

once @denesb confirm it's in place,

we'll need to backport 
https://github.com/scylladb/scylla-cluster-tests/pull/6463

**Comment by denesb** [comment]
> so it's there in 5.2, and we can backport the usage of the new tool into SCT branch-5.2 ?

Well... I backported the schema auto-detect, but not the bunch of follow-up fixes we found when using SCT w.r.t. EAR (enterprise). So maybe if you enable it in SCT, you will start hitting problems.
