### ISSUE TITLE
sstableloader without prepared statements is not loading data 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla-tools-java#67]
scylla scylladb/scylla@9d27045c76be7c4a5653a91ce105ca755cd738f9
scylla-tools-java b073229b0f501d60df4c3bd19a6f2affcafe35ca

running 
sstableloader_test.TestMigration_with_2_1_x_prepared.migrate_sstable_to_check_consistency_test

passes succesfully

running 

nosetests -v -s sstableloader_test.py:TestMigration_with_2_1_x.migrate_sstable_to_check_consistency_test

fails

the difference between the two is the addition of the `-nx` flag (no prepared statemements

**Comment by elcallio** [comment]
It seems the driver does not handle statements using named values when doing batch statements. 
Can fix this in a few ways: 
1.) Disallow batch w.o. prepared
2.) Patch the statements iff not prepared and batch
3.) Disallow not using prepared

I'd suggest 3 actually at this point. Both because we've pretty much settled on using prepared statements at this point, but also because right now we actually have broken type handling in the non-prepared case (same codec issues as with prepared ones, we only survive because the driver up until now does not even bother to check variables), and it would be nice to reduce the amount of code paths.
