### ISSUE TITLE
sstableloader should fail ASAP if trying to import MV tables

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla-tools-java#75]
Scylla will not support importing MV tables from Cassandra.

If anyone tries, we should fail preemptively, instead of waiting for an exception to happen.

@elcallio

**Comment by elcallio** [comment]
We don't really know the "type" of the underlying table in a sstable file, esp. not one from 2.x series. 
The schema is derived from info in scylla, so technically you could have a normal table named as a materialized view in the original server, and we will be none the wiser. Otoh, iff schema and name match, but it is not a view, why not allow import?

I've sent a patch to just be more verbose about not finding a table (maybe because it is a view). The import should fail (and already does) if the target either does not exist or is a view (to the driver - which I hope we present as).

**Comment by DoronArazii** [comment]
@elcallio I closed it, if it's still relevant please reopen
